version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: news-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - news-network

  nginx:
    image: nginx:alpine
    container_name: news-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - news-network

  mysql:
    image: mysql:8.0
    container_name: news-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - news-network

  redis:
    image: redis:alpine
    container_name: news-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - news-network

networks:
  news-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local